# -*- coding: utf-8 -*-
"""Model_tflit_Script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18u9zRb1psmedFiHJ8-hXpjb3QrtZ2wGC
"""

import tensorflow as tf
import numpy as np
from PIL import Image
MODEL_PATH = "/content/drive/MyDrive/Motmaen/Models/model_v5_fine_tuned_int8.tflite"
interpreter = tf.lite.Interpreter(model_path=MODEL_PATH)
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
class_names = [
    "Fattah",
    "Fool",
    "Hawawshy",
    "Koshari",
    "Kunafa",
    "Mahshy El Kosa",
    "Ptata",
    "Taameya",
    "Umm Ali"
]
def predict(image_path):
    img = Image.open(image_path).convert("RGB").resize((224, 224))
    img_array = np.expand_dims(np.array(img, dtype=np.uint8), axis=0)
    interpreter.set_tensor(input_details[0]['index'], img_array)
    interpreter.invoke()
    output_data = interpreter.get_tensor(output_details[0]['index'])[0]
    pred_idx = int(np.argmax(output_data))
    confidence = float(np.max(output_data))
    print("===================================")
    print(f"Predicted Dish : {class_names[pred_idx]}")
    print(f"Confidence     : {confidence}%")
    print("===================================")

if __name__ == "__main__":
    test_image_path = "/content/drive/MyDrive/Motmaen/food_photos/food photos/Fool/test/aug_0_3532.jpg"
    predict(test_image_path)

